# Generated by Django 5.2.3 on 2025-07-08 18:19

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'verbose_name_plural': 'Churches'},
        ),
        migrations.AddConstraint(
            model_name='church',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('city'), models.F('state'), name='unique_church_name_city_state'),
        ),
    ]
