# Generated by Django 5.2.3 on 2025-07-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="profile",
            name="street_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="zipcode",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
