# Generated by Django 5.2.3 on 2025-07-23 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_invitecode_options_alter_profile_options_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="MutualInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expressed_by",
                    models.CharField(
                        choices=[("candidate", "Candidate"), ("church", "Church")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expressed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expressed_mutual_interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mutual_interests",
                        to="api.job",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mutual_interests",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job_listing", "profile", "expressed_by"),
                        name="unique_interest_per_side",
                    )
                ],
            },
        ),
    ]
